### ISSUE TITLE
pm_sponsorUserOperation calldata hex contains 'NaN'

### ISSUE THREAD

**Issue by utgarda** [pimlicolabs/permissionless.js#110]
Executing a write function on a contract
with

* viem 2.7.1
* permissionless 0.0.35
  results in

```logs
Validation error: not valid hex data at "params[0].callData"
```

Following [Use Kernel Account how-to](https://docs.pimlico.io/permissionless/how-to/accounts/use-kernel-account) very closely gets me these logs:

```logs
Error: The method does not exist / is not available.

URL: https://api.pimlico.io/v2/arbitrum-sepolia/rpc?apikey=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Request body: {"method":"pm_sponsorUserOperation","params":[{"sender":"0x6DcEEd434A4356e51583952974e228FCEbb64Db6","nonce":"0x1","initCode":"0x","callData":"0x519454470000000000000000000000009cc9ee1f0009025a981f2a9d785b648fdf6f4d1d0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000084fc9c5dfb0000000000000000000000000000000000000000000000000000000000000NaN00000000000000000000000001e36d100dba45e62924307adf7c42c9c60d6214000000000000000000000000187de399100aa962f209aa78621f5138aca6111f00000000000000000000000000000000000000000000000000005838928b100000000000000000000000000000000000000000000000000000000000","paymasterAndData":"0x","signature":"0x00000000fffffffffffffffffffffffffffffff0000000000000000000000000000000007aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1c","maxFeePerGas":"0x7270e00","maxPriorityFeePerGas":"0x0","callGasLimit":"0x0","verificationGasLimit":"0x0","preVerificationGas":"0x0"},"0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789"]}

Details: Validation error: not valid hex data at "params[0].callData"
Version: viem@2.7.1
```

**Comment by pavlovdog** [comment]
Hey! How did you build the `callData`? It has `NaN` in the middle of it.

**Comment by pavlovdog** [comment]
Which transaction are you sending? Simple ETH transfer works fine

**Comment by utgarda** [comment]
> Which transaction are you sending? Simple ETH transfer works fine

Hi! Nice to know. It was a tx executing a write function, same way as in the tutorial
https://docs.pimlico.io/permissionless/how-to/accounts/use-kernel-account#send-a-transaction
Data encoded with Viem, no `NaN` in hex representation.

**Comment by pavlovdog** [comment]
Can you share the code? Also, try to encode the call data manually and put it into the `data` field.

**Comment by utgarda** [comment]
Thanks for the suggestions, tried all that. I'd share the code as well, but it was 2 months ago, so I picked another AA library and that code is lost by now. Admittedly, I was new to both AA and TypeScript then, might have missed something.
