### ISSUE TITLE
Wagmi Connectors: `useWalletClient` not working

### ISSUE THREAD

**Issue by johanneskares** [pimlicolabs/permissionless.js#133]
I'm successfully running the Wagmi Demo: `packages/wagmi-test-demo`

I'm doing a small modification and adding in `App.tsx`

```typescript
const { data: client } = useWalletClient()
```

and changing the `sendTransactionOnButtonPress` to

```typescript
const sendTransactionOnButtonPress = async () => {
    client?.sendTransaction({
        to: "0xe0a942ff2e1724A2fe10627728bE327a43fE8C26",
        value: 100n,
        chain: sepolia,
    });
};
```

I'm getting this error.

```
TransactionExecutionError: The method does not exist / is not available.
```

**Comment by johanneskares** [comment]
I think I find the underlying issue in @wagmi/core

https://github.com/wevm/wagmi/issues/3640

**Comment by pavlovdog** [comment]
Hey! It seems to be working, closing this
