### ISSUE TITLE
custom endpoint address

### ISSUE THREAD

**Issue by masha256** [pimlicolabs/permissionless.js#156]
I am working on a private chain with a custom endpoint address. It conforms to v0.7, but it seems permissionlessjs makes some strong assumptions that an entrypoint is always one of the two widely deployed entrypoint addresses. Am I missing something that would allow me to have a custom entrypoint address?

**Comment by pavlovdog** [comment]
Unfortunately no, only two standard addresses are supported at the moment. We will likely add the support soon.
