### ISSUE TITLE
Compile error This expression is not callable. Type 'never' has no call signatures.

### ISSUE THREAD

**Issue by asghaiermp** [pimlicolabs/permissionless.js#162]
I am getting this error when running npm run build for my nodejs app

node_modules/permissionless/utils/getAction.ts:10:9 - error TS2349: This expression is not callable.
  Type 'never' has no call signatures.

 10         (
            ~
 11             client as Client & {
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
 13             }
    ~~~~~~~~~~~~~
 14         )[actionName]?.(...params) ?? action(client, ...params)
    ~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/permissionless/utils/getAction.ts:10

Here is my ts.config file

```
{
  "compilerOptions": {
    "module": "CommonJS",
    "target": "ES2021",
    "noImplicitAny": true,
    "removeComments": true,
    "preserveConstEnums": true,
    "outDir": "./build",
    "sourceMap": true,
    "skipLibCheck": true,
    "resolveJsonModule":true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "**/*.spec.ts"]
}
```

**Comment by kristofgazso** [comment]
on it!

**Comment by pavlovdog** [comment]
Hey! Can you share the code? Also, try to use the `tsconfig.json` from the [tutorial](https://github.com/pimlicolabs/tutorial-template/blob/main/tsconfig.json).

**Comment by asghaiermp** [comment]
I have tried that but still getting similar errors

here is the code we are using for AA through ZeroDev SDK

import { polygonMumbai, polygon } from "viem/chains"
import { createPublicClient, http, Hex, keccak256, toHex } from "viem"
import { getKernelAddressFromECDSA } from "@zerodev/ecdsa-validator"
import { BlockchainTypes, ContractEnvironment } from "@mentaport/serverless-common"
import { getCertificatesBlockchainEnv } from "./blockchainEnv"
 
/**
 *  Function to create a wallet from an email using account abstraction
 *
 * @param {email} email of user
 * 
 * @returns {string} Returns smart contract wallet address
 */
export async function generateWalletFromEmail(email:string, environment: ContractEnvironment, chain: BlockchainTypes):Promise<string> {

  const config = getCertificatesBlockchainEnv(environment,chain);
  // hash the customer email and convert to BigInt so always same index
  const index = BigInt(keccak256(toHex(email)));

  const publicClient = createPublicClient({
    chain: environment === ContractEnvironment.Mainnet ? polygon : polygonMumbai,
    transport: http(config.RPC_URL),
  });

  const smartAccountAddress = await getKernelAddressFromECDSA({
    publicClient, 
    eoaAddress: config.eoaAddress as Hex, 
    index
  });

  return smartAccountAddress;
}

**Comment by pavlovdog** [comment]
Can't reproduce without these dependencies

```
import { BlockchainTypes, ContractEnvironment } from "@mentaport/serverless-common"
import { getCertificatesBlockchainEnv } from "./blockchainEnv"
```

Also, it seems that you forgot to pass `entryPointAddress` to a `getKernelAddressFromECDSA`.

**Comment by asghaiermp** [comment]
@pavlovdog to reproduce here is a modified version of the code

```
import { polygon, polygonAmoy } from "viem/chains"
import { createPublicClient, http, Hex, keccak256, toHex } from "viem"
import { getKernelAddressFromECDSA } from "@zerodev/ecdsa-validator"
 
/**
 *  Function to create a wallet from an email using account abstraction
 *
 * @param {email} email of user
 * 
 * @returns {string} Returns smart contract wallet address
 */
export async function generateWalletFromEmail(email:string):Promise<string> {

  // hash the customer email and convert to BigInt so always same index
  const index = BigInt(keccak256(toHex(email)));

  const publicClient = createPublicClient({
    chain: polygonAmoy,
    transport: http(`https://polygon-amoy.g.alchemy.com/v2/${API_KEY}`),
  });

  const smartAccountAddress = await getKernelAddressFromECDSA({
    publicClient, 
    eoaAddress: 'ANY EOA ADDRESS', 
    index
  });

  return smartAccountAddress;
}
```

**Comment by pavlovdog** [comment]
I still can't reproduce this, it works on my setup. Can you share the minimal repo, including all the involved versions (node/package manager/etc) and a run command?

**Comment by yaniferhaoui** [comment]
Hi, I have this kind of compile error me too, did you figured out the solution @asghaiermp ?

**Comment by plusminushalf** [comment]
This is not relevant post `permissionless@0.2.x`
