### ISSUE TITLE
Seperating waitForUserOperationReceipt from sendTransaction

### ISSUE THREAD

**Issue by tre-dev** [pimlicolabs/permissionless.js#196]
Hey, thanks for providing the library. I have a small feature request.

I would like to call `smartAccountClient.sendUserOperation` and `smartAccountClient.waitForUserOperationReceipt` within `smartAccountClient.sendTransaction` separately.

Reason for this is that if `waitForUserOperationReceipt` fails, I only want to retry that one, rather than sending the whole transaction again and possibly double spending.

Optimally, the `sendUserOperation` wrapper also includes all of this code: https://github.com/pimlicolabs/permissionless.js/blob/89e8339e90d350428ed8bc68609dc9d7f60f5307/packages/permissionless/actions/smartAccount/sendTransaction.ts#L89-L134

The same would also go for `sendTransactions`.

**Comment by plusminushalf** [comment]
Hey so we can't modify the behaviour of `sendTransaction` unfortunately. Also I think we are missing a timeout in `sendTransaction` and I think we should add it.

What I would suggest is that you use `prepareUserOperation` and then call `sendUserOperation`. `sendUserOperation` returns a `userOpHash` and then using that as an input, you can call `waitForUserOperationReceipt` with custom timeout.

**Comment by tre-dev** [comment]
Hey, thanks for the quick reply!

Quick question regarding `sendUserOperation`. In your code, `middleware` is taken from `args`, which is `smartAccountClient.account` and parameters. I can't seem to access the middleware from the smartAccountClient. Should I just use the object? `{ sponsorUserOperation: cloudPaymaster.sponsorUserOperation }`

```

const smartAccountClient = createSmartAccountClient({
  account,
  entryPoint: ENTRYPOINT_ADDRESS_V06,
  chain: BASE_CHAIN,
  bundlerTransport: http(this.baseRpcUrl),
  middleware: {
     sponsorUserOperation: cloudPaymaster.sponsorUserOperation,
  },
});
    
await smartAccountClient.sendUserOperation({ userOperation, account: smartAccountClient.account, middleware: ??? })
```

**Comment by plusminushalf** [comment]
hey is you do `smartAccountClient.sendUserOperation` the middleware will still be attached so you don't have to worry about it. If you need the code where we do it it's here - https://github.com/pimlicolabs/permissionless.js/blob/846570606c956288334b28a6c85401593e640afc/packages/permissionless/clients/decorators/smartAccount.ts#L506

**Comment by tre-dev** [comment]
Ah great, thanks for confirming!
