### ISSUE TITLE
Handling of erroneous transactions

### ISSUE THREAD

**Issue by ennioVisco** [pimlicolabs/permissionless.js#199]
Consider this basic use case: I have a 0.5 ETH balance in my smart account, but I try to transfer 1ETH.

If I try to `sendTransaction` from a Viem client linked to an EOA, the operation fails before sending the transaction. 

Conversely, if I do the same in a Smart Account (in our case via Kernel), the transaction is sent (and paid) "successfully", but checking on Etherscan we see that the UserOp is ofc reverted.

What would be the proper way of simulating the UserOp before actually sending it to the blockchain?

Shouldn't the UserOp be simulated as well, according to the spec? https://eips.ethereum.org/EIPS/eip-4337#-eth_estimateuseroperationgas

**Comment by plusminushalf** [comment]
Hey so currently bundlers have varied behaviour and not all revert. At pimlico, we do revert when using EntryPoint 0.7 but it is extremely difficult to revert with EntryPoint 0.6. So if you are trying and new, I would suggest using EntryPoint 0.7 with Pimlico.

**Comment by ennioVisco** [comment]
Thanks for the quick response! 

We are, indeed, using entrypoint V7.

To be clear, we don't necessarily need to have high-level apis like `sendTransaction`.

It would just be nice to have some way to stimulate the return value of the content of the UserOp :/

**Comment by plusminushalf** [comment]
Hey which bundler are you using? if you are using V7, then either during `smartAccountClient.sendTransaction` or `smartAccountClient.prepareUserOperation` you should have received the error. 

Can you share:

1. Which bundler are you using
2. If it's Pimlico, can you share the transaction Hash. I will be more than happy to take a look at the logs to see why did it not revert during estimation.

**Comment by ennioVisco** [comment]
> Hey which bundler are you using? if you are using V7, then either during `smartAccountClient.sendTransaction` or `smartAccountClient.prepareUserOperation` you should have received the error.
> 
> Can you share:
> 
> 1. Which bundler are you using
> 2. If it's Pimlico, can you share the transaction Hash. I will be more than happy to take a look at the logs to see why did it not revert during estimation.

Yes, we are using Pimlico :).
An example of the transactions where this happened is this one: https://sepolia.etherscan.io/tx/0x3b8dc2b6e949abb8b8dca23ee24911b050cae9b94f0e2a2b2a88da8b75303b47

**Comment by plusminushalf** [comment]
Ah okay, I have figured out the issue. So during simulation we do override balance of the sender so that simulation succeeds irrespective of the balance. We do so for the use case where a lot of dapps want to estimate the gas and show the user how much it will cost to send the transaction. And for that we do need a successful estimation. We do revert on every other thing except for when there is not enough balance. 

Let me think over what would be the best way to solve it.

**Comment by ennioVisco** [comment]
@plusminushalf hey, thanks for closing the issue, can I ask you how has it been addressed?

**Comment by plusminushalf** [comment]
Hey it's not the most elegant, also this issue is not of `permissionless` but rather of our alto bundler. so will be taking it there.

Also temporary solution can be:

```typescript
               const userOperation =
                    await smartClient.prepareUserOperationRequest(
                        {
                            userOperation: {
                                callData:
                                    await smartClient.account.encodeCallData({
                                        to: zeroAddress,
                                        value: 0n,
                                        data: "0x"
                                    })
                            }
                        },
                        {
                            [smartClient.account.address]: {
                                balance: 0n // or the actual balance
                            }
                        }
                    )

                userOperation.signature =
                    await smartClient.account.signUserOperation(userOperation)

                smartClient.sendUserOperation({ userOperation })
```
