### ISSUE TITLE
signerToEcdsaKernelSmartAccount doesn't work for Blast

### ISSUE THREAD

**Issue by cstoneham** [pimlicolabs/permissionless.js#219]
### Description
Creating Kernel wallets returns zero address on Blast network.

### Details
`"permissionless": "^0.1.30",`

### Repro Steps
```
const privateKey = generatePrivateKey();
const publicClient = createPublicClient({
        chain: blast,
        transport: http(rpcUrl),
      });
const account = await signerToEcdsaKernelSmartAccount(client, {
      entryPoint: ENTRYPOINT_ADDRESS_V06,
      signer,
    });
```

**Comment by cstoneham** [comment]
would also be great to have a simple test suite for each chain to just make sure the address exists everywhere

**Comment by dqian** [comment]
need this working as well

**Comment by plusminushalf** [comment]
Kernel is unfortunately not deployed on blast, will open this again once it is deployed by Zerodev team.
