### ISSUE TITLE
`prepareUserOperationRequest` ignores `middleware` parameter

### ISSUE THREAD

**Issue by matthiasgeihs** [pimlicolabs/permissionless.js#257]
https://github.com/pimlicolabs/permissionless.js/blob/0ba75d76d7a628c410e4df4702100bff34398b75/packages/permissionless/clients/decorators/smartAccount.ts#L477-L485

`client.prepareUserOperationRequest` accepts a `middleware` parameter. This is then embedded in `args`. However, because `args` is overwritten by the `middleware` from `smartAccountActions({middleware})`, this `middleware` parameter in `prepareUserOperationRequest({middleware})` actually does not have an effect.

**Comment by plusminushalf** [comment]
This is no more valid in `permissionless@0.2.x`
