### ISSUE TITLE
sponsorUserOperation fails with TypeError

### ISSUE THREAD

**Issue by nerderlyne** [pimlicolabs/permissionless.js#26]
```
  const sponsorUserOperationResult = await paymasterClient.sponsorUserOperation(
    {
      userOperation,
      entryPoint,
    },
  )
```

`Error: TypeError: Cannot convert undefined to a BigInt`

On calling "pm_sponsorUserOperation" method directly I found preVerificationGas, verificationGasLimit, and callGasLimit are undefined but valid paymasterAndData, this throws `sponsorUserOperation`.

**Comment by plusminushalf** [comment]
Which service are you using? Pimlico or Stackup?

**Comment by plusminushalf** [comment]
This issue has been pending for an extended period, so closing for now. Please don't hesitate to reopen if you're still experiencing the problem.

**Comment by baiirun** [comment]
Hey @plusminushalf. I'm also running into this issue when attempting the Tutorial 1 on Polygon. Polygon doesn't support the V2 API or the V07 entry point so I'm having to go back and use the V1 API and V06 entrypoints.

Looks like it fails here when parsing the response for v06.

https://github.com/pimlicolabs/permissionless.js/blob/f1aff84dae15c675da5de469ea7689df908d5d3c/packages/permissionless/actions/pimlico/sponsorUserOperation.ts#L118

![CleanShot 2024-03-26 at 12 43 58@2x](https://github.com/pimlicolabs/permissionless.js/assets/26263630/fd39cb7b-a1c7-41cf-9eb8-433ec6e58211)
