### ISSUE TITLE
EstimateUserOperationGasError and SendUserOperationError cannot override cause

### ISSUE THREAD

**Issue by ctrlc03** [pimlicolabs/permissionless.js#266]
Currently, I am unable to use libraries built on top of permissionless.js like @zerodev/sdk due to this error present at https://github.com/pimlicolabs/permissionless.js/blob/main/packages/permissionless/errors/estimateUserOperationGas.ts#L13 and https://github.com/pimlicolabs/permissionless.js/blob/main/packages/permissionless/errors/sendUserOperation.ts#L13

```
This member cannot have an 'override' modifier because it is not declared in the base class 'BaseError'.
```

Looks like an easy fix would be removing the `override` keyword

**Comment by plusminushalf** [comment]
Which version of viem and perissionless are you using? Also can you share the tsconfig?

**Comment by ctrlc03** [comment]
> Which version of viem and perissionless are you using? Also can you share the tsconfig?

Hey thanks for the reply.

viem: 2.16.3
permissionless: 0.1.44

Tsconfig: 
```json
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true
  },
```

**Comment by plusminushalf** [comment]
Can you try `ES2021`

**Comment by plusminushalf** [comment]
I think this is a good resource on how to map based on your node version - https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping

**Comment by ctrlc03** [comment]
> Can you try the following adjustments:
> 
> ```
>          "module": "NodeNext",
>         "target": "ES2021", // Setting this to `ES2021` enables native support for `Node v16+`: https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping.
>         "lib": [
>             "ES2022", // By using ES2022 we get access to the `.cause` property on `Error` instances.
>             "DOM" // We are adding `DOM` here to get the `fetch`, etc. types. This should be removed once these types are available via DefinitelyTyped.
>         ],
>         ```
> ```

Thanks! no chance that can be fixed? I would rather not go down this route of using esm if possible.

**Comment by plusminushalf** [comment]
Hey so cause was introduced in ES2022, for a detailed Explanation you can checkout here - https://stackoverflow.com/a/73394582

I understand these versions can be frustrating I hope this will help you a little.

<img width="753" alt="image" src="https://github.com/user-attachments/assets/69eda26c-3455-4e2d-aad6-2310470a939f">

**Comment by ctrlc03** [comment]
> Hey so cause was introduced in ES2022, for a detailed Explanation you can checkout here - https://stackoverflow.com/a/73394582
> 
> I understand these versions can be frustrating I hope this will help you a little.
> 
> <img alt="image" width="753" src="https://private-user-images.githubusercontent.com/5251472/358657687-69eda26c-3455-4e2d-aad6-2310470a939f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4Mjg2ODIsIm5iZiI6MTcyMzgyODM4MiwicGF0aCI6Ii81MjUxNDcyLzM1ODY1NzY4Ny02OWVkYTI2Yy0zNDU1LTRlMmQtYWFkNi0yMzEwNDcwYTkzOWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTZUMTcxMzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjQ4OWE1MDgxZjZjYjA5NjA1MDBmMGUwMTc1ZTk0N2IxNTg4ZmYwNGZhMjhjMWNlMjMzOTE5NjRkNDMzZDkwYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Kdk0HELufEM5_bTSSBcAwVHG4LKdXeeTxOBrUyuR6Hs">

gotcha, will amend on my side, appreciate your help with this! 🙏  I'll close the issue
