### ISSUE TITLE
`createSmartAccountClient` not compatible with viem's `Client`

### ISSUE THREAD

**Issue by johanneskares** [pimlicolabs/permissionless.js#270]
Shouldn't this compile?

```ts
import { Client } from "viem";
import { createSmartAccountClient } from "permissionless";

const client: Client = createSmartAccountClient({...});
```

I'm using Viem 2.19.9 and Permissionless 0.1.45

**Comment by plusminushalf** [comment]
Hey which version of viem are you using?

**Comment by johanneskares** [comment]
Ah sorry, updated in the original message

**Comment by johanneskares** [comment]
The reason: I'm trying to create a custom Connector for Wagmi, and it expects a `Client` object in its `getClient` function. For now this doesn't compile and I have to go through `any`, even though the implementation works.

**Comment by plusminushalf** [comment]
I see, so permissionless is not only compatible till 2.17.11 We are working on a new permissioness 0.2 release that will be compatible from 2.18.0 and onwards.
