### ISSUE TITLE
Upgrade sdk to support rhinestone latest safe7579 contracts 

### ISSUE THREAD

**Issue by yoanslvy** [pimlicolabs/permissionless.js#298]
Hello guys!

It looks like rhinestone just published their latest prod version of their safe 7579 contract, I tried to update theses addresses into the permissionless sdk but it does not seem to work.

Here are the latest versions:
Safe7579 Adapter = 0x7579F9feedf32331C645828139aFF78d517d0001
Safe7579 Launchpad  0x7579011aB74c46090561ea277Ba79D510c6C00ff

Would be nice if it could get upgraded !

**Comment by plusminushalf** [comment]
Hey thanks for informing this, will take a look at this!

**Comment by Olowojaye** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by yoanslvy** [comment]
Just added the fix on a PR: https://github.com/pimlicolabs/permissionless.js/pull/314
Free to discuss it if needed !
