### ISSUE TITLE
The intersection 'Client' was reduced to 'never' because property 'cacheTime' has conflicting types in some constituents

### ISSUE THREAD

**Issue by 0xtiki** [pimlicolabs/permissionless.js#331]
I get an error when following this tutorial https://docs.pimlico.io/permissionless/tutorial/tutorial-1. It works if I install the demo app but when I try to do the same in a nestjs app I get a type error about cacheTime property on the public client.     

Relevant Code:
```
const account = await toSafeSmartAccount({
      client: publicClient, ---> this part throws the error
      owners: [privateKeyToAccount(privateKey)],
      entryPoint: {
        address: entryPoint07Address,
        version: '0.7',
      }, // global entrypoint
      version: '1.4.1',
    });
```
        
I have a repo with the problem here: https://github.com/0xtiki/permissionless/blob/main/src/app.service.ts

**Comment by 0xtiki** [comment]
looks like this fixed it:

```
const account = await toSafeSmartAccount({
      client: publicClient as Client,
      owners: [privateKeyToAccount(privateKey)],
      entryPoint: {
        address: entryPoint07Address,
        version: '0.7',
      }, // global entrypoint
      version: '1.4.1',
    });
```

**Comment by mouseless0x** [comment]
Hey, could you try turning strict mode on in your tsconfig, seems related to [viem/issues/871](https://github.com/wevm/viem/issues/871)

**Comment by 0xtiki** [comment]
> Hey, could you try turning strict mode on in your tsconfig, seems related to [viem/issues/871](https://github.com/wevm/viem/issues/871)

Yes it seems to be the same issue, thanks for the response. Strict mode doesn't fix it unfortunately.

**Comment by 0xtiki** [comment]
Do you think the other TS errrors are caused by the same issue? For example `smartAccountClient.sendTransaction` throws `Type instantiation is excessively deep and possibly infinite.`

It is in https://github.com/0xtiki/permissionless/blob/main/src/app.service.ts

**Comment by 0xtiki** [comment]
For anybody else who might run into this, this seems to fix it: https://github.com/wevm/viem/issues/3021
