### ISSUE TITLE
Module '"permissionless/clients/pimlico"' has no exported member 'createBundlerClient'

### ISSUE THREAD

**Issue by francelwebdev** [pimlicolabs/permissionless.js#38]
Module '"permissionless/clients/pimlico"' has no exported member 'createBundlerClient'

**Comment by plusminushalf** [comment]
You can use:
`import { createBundlerClient } from 'permissionless'`
and pass in Pimlico's URL.

If you want to use Pimlico specific actions, you will have to use:
`import { createPimlicoBundlerClient } from "permissionless/clients/pimlico"`
