### ISSUE TITLE
Feature request: Set timeout & polling interval when sending transactions from a SmartAccountClient

### ISSUE THREAD

**Issue by KONFeature** [pimlicolabs/permissionless.js#45]
It could be nice to have the options to specify the polling interval & timeout when calling `.sendTransaction(...)` and `.sendTransactions(...)` method via `SmartAccountClient`

Something like that:
```
smartAccountClient.sendTransactions({
    transactions,
    polling: {
        intervalInMs: 4_000,
        timeoutInMs: 120_000
    }
})
```

Btw, having a single entry point for single & batched could be awesome, like supporting in the `.sendTransactions(...)` method an array or a single tx

**Comment by plusminushalf** [comment]
Hey we recommend using `sendUserOperation` if you want to control the polling intervals. We can't modify the action `sendTransaction` or `sendTransactions`.
