### ISSUE TITLE
Unable to resolve file when using React Native 

### ISSUE THREAD

**Issue by shafarizkyf** [pimlicolabs/permissionless.js#61]
Hi guys,
I'm facing an issue when using React Native. The cause is that this library uses 'import '.js'' while the file itself is '.ts'. This doesn't happen when using plain Node.js. Could you please advise on how to resolve this? Thank you.

<img width="434" alt="image" src="https://github.com/pimlicolabs/permissionless.js/assets/20674388/6b88d6b8-3200-4943-af04-f71dd781e462">

**Comment by plusminushalf** [comment]
Do you have some boilerplate code that you can help me with this?

**Comment by shafarizkyf** [comment]
> Do you have some boilerplate code that you can help me with this?

thank you for your swift response.
hopefully this helps: https://github.com/shafarizkyf/react-native-miza/tree/permissionless 

after the onboarding screen it should navigate to login and crash (because this [import line](https://github.com/shafarizkyf/react-native-miza/blob/permissionless/src/screens/AuthScreen/LoginScreen.tsx#L27))

**Comment by plusminushalf** [comment]
Same as - https://github.com/pimlicolabs/permissionless.js/issues/67#issuecomment-1880086050

**Comment by shafarizkyf** [comment]
> This looks like not all platforms support the `exports` in `package.json`.
> 
> For example, It is still experimental in Metro - [facebook/metro#670](https://github.com/facebook/metro/issues/670)
> 
> How to have a temp fix for the project - https://reactnative.dev/blog/2023/06/21/0.72-metro-package-exports-symlinks#package-exports-support-beta
> 
> Or:
> 
> ```ts
>  import { ... } from 'permissionless/_esm/..' instead of just from 'permissionless' if that helps for the future
> ```
> 
> ^ I know this is bad fix I am looking into better fix or enable the experimental feature.

thank you, for now I'm using `permissionless/_esm/..` solution

**Comment by emzet93** [comment]
Hey @plusminushalf, is there any progress on it?

**Comment by Kyle772** [comment]
+1 I think it is possible to provide RN support here given the above work around by @plusminushalf

**Comment by ialmanzaj** [comment]
+1 same error

**Comment by asgarovf** [comment]
It required me to fork the package and fix the imports. You can check out https://www.npmjs.com/package/@getclave/permissionless
