### ISSUE TITLE
Missing js output files 

### ISSUE THREAD

**Issue by jinhongkuan** [pimlicolabs/permissionless.js#67]
Tried to compile nodejs project that imports from `permissionless/clients/pimlico` and `permissionless/accounts` into binary form, with pkg. Ran into error that those modules were missing. Resolved by manually navigating into those folders and transpiling TS into JS.

**Comment by jinhongkuan** [comment]
yes I changed directory to the mentioned folders and ran `tsc`. make sure that your root tsconfig doesn't have outDir set when this is run so that the transpiled js files appear right next to ts files.

**Comment by plusminushalf** [comment]
This looks like not all platforms support the `exports` in `package.json`.

For example, It is still experimental in Metro - https://github.com/facebook/metro/issues/670

How to have a temp fix for the project - https://reactnative.dev/blog/2023/06/21/0.72-metro-package-exports-symlinks#package-exports-support-beta

Or:
```typescript
 import { ... } from 'permissionless/_esm/..' instead of just from 'permissionless' if that helps for the future
```
^ I know this is bad fix I am looking into better fix or enable the experimental feature.
